package models

type Beego_json struct {
	Orm_debug        string
	Db_name_mhsy     string
	Db_name_mhsy_en  string
	Db_driver_mysql  string
	Db_using_default string
	Db_using_mhsyen  string
	Db_user          string
	Db_password      string
	Db_protocol      string
	Db_ip            string
	Db_port          string
	Base_dir         string
	Proj_dir         string
	Web_url          string
	Bo_lang          string
	Gan_tan          string
	Quan_a           string
	Jing_hao         string
	Mei_yuan         string
	Bai_fen          string
	Cheng_fang       string
	Bing_qie         string
	Xing_hao         string
	Zuo_yuan_kuo     string
	You_yuan_kuo     string
	Xia_hua          string
	Jia_hao          string
	Zuo_da_kuo       string
	You_da_kuo       string
	Mao_hao          string
	Shuang_yin       string
	Zuo_jian_kuo     string
	You_jian_kuo     string
	Wen_hao          string
	Shu_xian         string
	Tilde            string
	Jian_hao         string
	Deng_hao         string
	Zuo_fang_kuo     string
	You_fang_kuo     string
	Fan_xie_xian     string
	Dan_yin          string
	Fen_hao          string
	Xie_xian         string
	Ju_hao           string
	Dou_hao          string
	Pager_size       string
	Jwt_mima         string
	Jwt_yan          string
}
type Column_props struct {
	Name    string
	Type    string
	Length  int64
	Comment string
	Tables  []string
}
